apiVersion: v1
kind: PersistentVolume
metadata:
  name: wppv
  labels: 
    volume-type: wp
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /root/nfs/wp
    server: 192.168.1.200
