apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv
  labels:
    volume-type: db
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /root/nfs/db
    server: 192.168.1.200
