apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
     matchLabels: 
      volume-type: db
